//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatosGastos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposdeGastos
    {
        public TiposdeGastos()
        {
            this.Productos = new HashSet<Productos>();
        }
    
        public System.Guid IdTipoGasto { get; set; }
        public string DescripcionGasto { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string UsuarioAlta { get; set; }
    
        public virtual ICollection<Productos> Productos { get; set; }
    }
}
